[package]
name = "parquet_diff"
version = "0.1.0"
edition = "2024"

[dependencies]
parquet = { version = "60.0.0", features = [ "arrow" ] }
clap = { version = "4.6.7", features = [ "derive" ] }
serde_json = "1.0.0"
hashbrown = { version = "0.17.1", features = [ "serde" ] }
fastbloom = "0.17.0"
rayon = "1.12.0"
string-interner = "0.20.0"
arrow-array = "60.0.0"
arrow = "60.0.0"